### ISSUE TITLE
Image utilities

### ISSUE THREAD

**Issue by gunner-dev** [hochschule-darmstadt/MetaAutoML#106]
Adapter and Controller code needs updates for image type.

- Prediction and evaluation functions are currently locked to tabular data.

**Comment by kampmichii** [comment]
- Controller reqiures rework for new image datasets.
- jinja2 templates needs to be updated(locked to tabular data)
- Blazor can not display information about dataset

The prior issues above have been determined to be too big to be in this tickets scope.
