### ISSUE TITLE
BE: AutoCVE implementation

### ISSUE THREAD

**Issue by SpaceDave42** [hochschule-darmstadt/MetaAutoML#14]
Implement integration for [AutoCVE](https://github.com/celiolarcher/AUTOCVE) a simple library which currently only supports classification.

**Comment by SpaceDave42** [comment]
[https://github.com/hochschule-darmstadt/MetaAutoML-Adapter-AutoCVE](https://github.com/hochschule-darmstadt/MetaAutoML-Adapter-AutoCVE) contains a preliminary implementation.
The implementation does work and is capable of producing and saving models but sadly due to the limitations of AutoCVE it only works on numerical classification datasets (like the phishing dataset used in the Hauptseminar).

This means that AutoCVE is unable to produce a result (or even finish) on the titanic dataset used in testing as it contains string categoricals.
Using pandas it is possible to convert these strings into integer categories. This enables AutoCVE to run on the dataset but no result is produced. According to the logs it cannot find any solutions whatsoever. So either the conversion (that was used) alters the information contained in the dataset or the failure happens at another point.

Therefore: For processing datasets that are not strictly numerical from the getgo additional work has to be done.

**Comment by BernhardHumm** [comment]
The concept described in the paper 
https://projects.fbi.h-da.de/~b.humm/pub/Humm%20Zender%20-%20Ontology_based_Meta_AutoML.pdf 
contains an analysis of the dataset and an ontology-based comparison with the 
requirements of an AutoML solution, followed by a pre-processing if needed. In 
this case: the Titanic dataset is analysed and non-numeric features are 
detected. In the ontology it is stated that AutoCVE requires numeric features 
only. Hence a conversion is performed as part of the ML pipeline for AutoCVE.

Whether this concept can already be implemented this semester is a matter of 
project planning. If not, there should be a notification that a pipeline for 
AutoCVE cannot be generated.

**Comment by SpaceDave42** [comment]
[b112185](https://github.com/hochschule-darmstadt/MetaAutoML-Adapter-AutoCVE/commit/b1121858cea4aa66c3c8969ce066b6fa75ad79f4) addresses this issue. This adds exception handling and error reporting so that if autoCVE crashes because of wrongly formatted data it doesn't crash the whole adapter and the user can try again.
