### ISSUE TITLE
Adapter AutoGluon text

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/MetaAutoML#151]
**Reason (Why?)**
Why do you want this feature? What goals should be achieved? Is your issue related to a problem?
- To make text classification and text regression possible for AutoGluon.

**Solution (What?)**
Describe the suggested solution (Don't repeat the reason again)
- Methods and tests for classification and regression will both be implemented.

**Out of scope**
Anything that is out of scope and shall not be implemented
-

**Relation to other Issues**
Provide additional context (link relevant issues)
-

**Acceptance criteria**
Describe acceptance criteria for testing (Don't repeat reason and solution again)
- Text classification and regression are supposed to produce a working model.
- Tests of the above functions are tested in a meaningful way and without errors.

**Comment by piafriehe** [comment]
Adapter Team 2: Julius und Pia übernehmen das

**Comment by piafriehe** [comment]
due to a bug in AutoGluon, this task can only be continued later
![image](https://user-images.githubusercontent.com/66680791/203780669-5236e067-8f04-448d-ba12-454d6f701a07.png)
