### ISSUE TITLE
UX Improvements Login Page

### ISSUE THREAD

**Issue by AnnaHlzhsr** [hochschule-darmstadt/MetaAutoML#183]
~1. (House Icon leads to Home for a second and then goes back to Login)~
~2. (Logo leads to Home for a second and then goes back to Login)~
~3. **No eye Icon in order to toggle show/hide password for users**~
~4. (Anmelden wird als Registirerung benutzt/ Fault just on German Login)~
~5. **Buttons not aligned**~
~6. **Old Logo still showing**~
~7. **No eye Icon in order to toggle show/hide password for users**~
~8. **No Password rules (Capial letters, special letter, etc.)**~
~9. **No arrow to go back to Login Page**~

**Comment by AnnaHlzhsr** [comment]
1 & 2 Solved on "UX Improvements Krzysztof Anna"-Branch
4 Solved by Julian on his Branch

**Comment by AnnaHlzhsr** [comment]
3. Solved

**Comment by Krystofido** [comment]
7. = 3. (So Solved)

**Comment by Krystofido** [comment]
5. Changed, I would advise talking about the options

**Comment by Krystofido** [comment]
4. Technically done, but doesn't change in debugger, consultation about debugging required

**Comment by Krystofido** [comment]
9. Replaced Home icon with Arrow icon (in Register Page)

**Comment by Krystofido** [comment]
8. Done, see #184
