### ISSUE TITLE
Bug: online prediction for tabular regression is missing rows

### ISSUE THREAD

**Issue by stjascme** [hochschule-darmstadt/MetaAutoML#204]
**Describe the bug**
When making an online prediction for tabular regression the resulting csv file is incomplete.
The test dataset used when the bug appeared had 99999 rows while the result of the online prediction file had only 79999 rows.

**To Reproduce**
1. Go to [this Kaggle Chellenge](https://www.kaggle.com/competitions/restaurant-revenue-prediction/data ) and download the data
2. Upload the train csv and start a training
3. Select the columns Id, Open Date and City to be ignored, City Group and Type to Category and leave the rest as is.
![grafik](https://user-images.githubusercontent.com/66828080/201485610-b7d8dd96-e0fb-4e8e-9389-071ebfed9851.png)
4. Configure the training as shown in the image:
![grafik](https://user-images.githubusercontent.com/66828080/201485785-1e521d9d-d4da-4b6d-ab6a-db6a2ec20194.png)
5. Click on the Autogluon Model
6. Click 'ADD LIVE DATASET' and select the test csv from the Kaggle zip
7. Download the result csv
8. Compare number of rows with the test csv.

**Expected behavior**
The resulting file should contain predictions for all rows of the submitted dataset.

**Comment by BernhardHumm** [comment]
I suspect that the 80/20 training/test split necessary for training is 
(mistakenly) also performed for prediction.
