### ISSUE TITLE
UX Improvements - Add allowed file types to list of selectable dataset-types

### ISSUE THREAD

**Issue by Krystofido** [hochschule-darmstadt/MetaAutoML#213]
Next to the name of the dataset type there should be a list of allowed file-types. Adding this in brackets "()" should probably suffice.

The current plan is adding the info to the comment column:
![grafik](https://user-images.githubusercontent.com/25965992/202440662-0c145a30-3864-4d9c-a536-bc6012b078b9.png)
![grafik](https://user-images.githubusercontent.com/25965992/202440759-ac94196d-cfbf-4e2f-a999-f709e9b8800d.png)

This entry should now have some split-symbol (like @,$, ... BUT NOT | as this symbol is used for something else). Then when you retrieve the data in the code you could turn the string into a map of substrings and get the wanted comment.

**Comment by AnnaHlzhsr** [comment]
<img width="256" alt="Bildschirmfoto 2022-11-17 um 12 16 23" src="https://user-images.githubusercontent.com/116272018/202442042-275b3eb4-0e32-45ec-ab7e-a640b10e3758.png">

Currently supported Datatypes per Datasets (File /MetaAutoML/frontend/src/Shared/Modules/BlazorBoilerplate.Theme.MudBlazor.Demo/Shared/Components/DrawerFooter.razor)
