### ISSUE TITLE
UX Improvements - Wiki Tooltips

### ISSUE THREAD

**Issue by Krystofido** [hochschule-darmstadt/MetaAutoML#227]
- [x] Connection Wikidata 
- [x] Connection Wikipedia
- [ ] Document Connections (WikiGrabber etc. into Wiki in GitHub -> frontend Architecture)
- [x] if no "seeAlso" then use "rdfs:comment"
- [ ] Implement the tooltips to everything what comes from the ontology (every dropdown etc.)
- [ ] Add wikipedia to new Chips of the Wizard team
- [x] Change all /wiki/ to /entity/
- [ ] Tooltip should stay present when hovered over and can integrate a hyperlink e.g. to the documentation page of an adapter.

**Comment by AnnaHlzhsr** [comment]
3. done
