### ISSUE TITLE
UX Improvements Datasets Page

### ISSUE THREAD

**Issue by AnnaHlzhsr** [hochschule-darmstadt/MetaAutoML#232]
1. Start in the wrong rhine sequence
2. Add another column with "Time"
3. Add icon suggests a could which is not true since no cloud add is implemented
4. It was suggested by a native English-speaking user that "upload" is more common than "add"
5. search does not start the moment user types (user needs to press enter)
6. search needs to be delted and enter needs to be pressed to show all datasets again

**Comment by AnnaHlzhsr** [comment]
Done, right? @Krystofido

**Comment by Krystofido** [comment]
Yes, it's basically good to go for a pull request 👍
