### ISSUE TITLE
Remove testdatasets from the main repo

### ISSUE THREAD

**Issue by JStGit** [hochschule-darmstadt/MetaAutoML#235]
**Reason (Why?)**
To avoid ballooning the the repo and to avoid license issues, we want to remove the test datasets from the main project repository.

**Solutions (What?)**
1. Idea: Integrate public test data that can be downloaded during the test run.

2. Idea: Create a private repository containing all the test datasets together with two python scripts, one to copy the files to the correct folders in the main project and one to remove them again.

**Relation to other Issues**
Related to issue #221

**Acceptance criteria**
I can load the test data and remove it after testing without the data beeing contained in the main repo.

@AlexanderZender is it possible to get a kaggle account from the university that can be shared by all?

**Comment by JStGit** [comment]
Hint for 1. Idea: 
https://www.kaggle.com/docs/api#interacting-with-datasets

**Comment by jnnks** [comment]
Fixed with https://github.com/hochschule-darmstadt/MetaAutoML/pull/244
