### ISSUE TITLE
Enable testdata upload directly from a URL

### ISSUE THREAD

**Issue by JStGit** [hochschule-darmstadt/MetaAutoML#237]
**Reason (Why?)**
We want to skip the process of first downloading a dataset only to upload it again.

**Solution (What?)**
Enable the uploader to process URLs directly.

**Acceptance criteria**
Data can be passed via a URL.

For Frontend Team:
Add a text field where the Link can be copied next to the dataset field in the upload popup. The two upload choices (data from local PC and URL) need to be mutually exclusive.

**Comment by JStGit** [comment]
To clarify:
- We need a way to get access to the desired data that should be pulled:
   1. API
   2. Web Scraping
- What sites do we want to support?

**Comment by JStGit** [comment]
Only accept Kaggle API calls or direct links to files (i.e. Dropbox or similar)

**Comment by BernhardHumm** [comment]
All download links that refer to a file in the respective format shall be supported – not individual sites, no web scraping, no API access
