### ISSUE TITLE
Live dataset upload does not work anymore

### ISSUE THREAD

**Issue by JStGit** [hochschule-darmstadt/MetaAutoML#282]
**Describe the bug**
The button to upload a live dataset does not work anymore and does currently nothing.

![grafik](https://user-images.githubusercontent.com/53482726/214040480-ded8275f-cebf-4df1-8a31-a0e909031428.png)

**Expected behavior**
The button should open the Upload popup to upload a new dataset.

**Comment by AlexanderZender** [comment]
fixed it, closing
