### ISSUE TITLE
Add a static ExplainerDashboard to the frontend using Iframe

### ISSUE THREAD

**Issue by JStGit** [hochschule-darmstadt/MetaAutoML#318]
**Reason (Why?)**
We do this in order to test the layout.  If the layout does not suit our names, we can develop our own.

**Solution (What?)**
Include a (for now static) dashboard in the frontend using Iframe. 

**Acceptance criteria**
The frontend shows the new ExplainerDashboard instead of the old static graphs.

**Comment by BernhardHumm** [comment]
Before starting implementing, an interface concept (using wireframes) should be developed, documented in this issue and reviewed by project management.
