### ISSUE TITLE
Benchmark - Verify training finished without errors

### ISSUE THREAD

**Issue by zavog** [hochschule-darmstadt/MetaAutoML#332]
Parent: #172 

Let the benchmark make sure that the training finished and that it was successful.

To be clarified:
What should happen if a dataset training failed? Should the whole benchmark cancel? Or should the dataset be listed as failed, but all other datasets should continue as if nothing happened?

**Comment by BernhardHumm** [comment]
I suggest continuing with a benchmark if one dataset failed.

**Comment by zavog** [comment]
Benchmark now waits for each training to finish and only terminates when all trainings for all datasets finished. If a training failed for any adapter, the whole training is considered to have failed, but other datasets are run anyway.
