### ISSUE TITLE
Implement testing/using a generated AutoML solution

### ISSUE THREAD

**Issue by al-becker** [hochschule-darmstadt/MetaAutoML#39]
can be done after #35

**Comment by al-becker** [comment]
suggestion for test fronted design
![test](https://user-images.githubusercontent.com/33692777/149054370-d7bcb4d7-d289-46e2-afe1-9b5caba2bcd8.png)
![test_results](https://user-images.githubusercontent.com/33692777/149054385-4c7f2155-f337-4173-bea2-d3aac2883ae2.png)

**Comment by l0rs123** [comment]
As integration test for testing the backend I recommend using RobotFramework as it's a module in python and can use python code out of the box without doing something fancy.
Via the .net package it might be also possible to interact with our frontend environment.
Maybe an idea to investigate in it?

**Comment by al-becker** [comment]
sure, to avoid misconception this ticket is about testing the generated automl models

**Comment by BernhardHumm** [comment]
Implementing unit tests makes sense.

But why implementing a GUI for testing instead of manually testing the GUI of 
the omaML app?
