### ISSUE TITLE
Continuous Testing

### ISSUE THREAD

**Issue by l0rs123** [hochschule-darmstadt/MetaAutoML#40]
For testing the PRs automatically it might be useful to implement a CT framework in our CI

**Comment by l0rs123** [comment]
[Robot_Concept.zip](https://github.com/hochschule-darmstadt/MetaAutoML/files/7852794/Robot_Concept.zip)
Robot Framework Concept

**Comment by l0rs123** [comment]
with pythonnet we can directly communicate with the c# functions using following commands:
![image](https://user-images.githubusercontent.com/92858146/149090801-8af36857-449a-4fd8-91ce-4916a27e1b35.png)
http://pythonnet.github.io/

**Comment by BernhardHumm** [comment]
Why calling Python from C#?

**Comment by l0rs123** [comment]
It's the other way around (calling C# from python). 
The idea was to have an Integration Test setup written in python:
- for testing the functionality between frontend (C#) and backend (Python) the pythonnet-package would come into place

We should discuss later in detail.
