### ISSUE TITLE
Training Model Configuration Panel

### ISSUE THREAD

**Issue by dominoxp** [hochschule-darmstadt/MetaAutoML#410]
**Describe the bug**
- [ ] The Configuration Panel is missing the target table rows information.
Selected Values are currently displayed with "True ? <name> :", either the formatting should be changed to be "<name>: <value>"
or boolean values could be visualised by checkmark ✅ ❌ icons if specific ml library was selected or not.

![grafik](https://github.com/hochschule-darmstadt/MetaAutoML/assets/13829738/2238c178-2ba7-4d28-a091-3dc34a2f9aa0)

**To Reproduce**
Steps to reproduce the behavior ((if applicable, add screenshots)):
1. Go to 'Past Trainings'
2. Select a past Training
3. Click on any trained Model

**Expected behavior**
The Target Rows being shown
The Selected Libraries being better formatted

**Comment by BernhardHumm** [comment]
Why don’t we go one step back and simplify the code for displaying the configuration altogether? My suggestion: simply show the JSON string with line breaks .
The configuration is something technical, so users interested in configuration should be able to read JSON.

**Comment by dominoxp** [comment]
The Target Field in TrainingConfigurationDto is empty when requesting from controller
apiClient.GetTraining(new GetTrainingRequestDto() { TrainingId = _model.Model.TrainingId })

The current view had only a syntax Problem with Blazor formatting, leading to not rendering properly.

**Comment by dominoxp** [comment]
Corrected Rendering Problems. The target field in GetTrainingResponseDto is empty when requesting from controller api by apiClient.GetTraining() on Training.Configuration.Target. Waiting on @AlexanderZender for changes in controller.
