### ISSUE TITLE
Home UI Improvement

### ISSUE THREAD

**Issue by dominoxp** [hochschule-darmstadt/MetaAutoML#411]
**Describe the bug**
A clear and concise description of what the bug is (if applicable, add screenshots)

- [x] The Recent Training table should have the same hight as the recent dataset table
Last time testing with master branch, the recent trainings did not show any entry for recent trainings

![grafik](https://github.com/hochschule-darmstadt/MetaAutoML/assets/13829738/995c11fa-9bc7-4d99-a2c2-0a191989df6e)

**To Reproduce**
Steps to reproduce the behavior ((if applicable, add screenshots)):
1. Go to 'Home'

**Expected behavior**
A clear and concise description of what you expect to happen.

**Comment by dominoxp** [comment]
I have fixed the Recent training tab size. https://github.com/hochschule-darmstadt/MetaAutoML/tree/411-home-ui-improvement
The Training list is currently not loading correctly if in the the apiclient GetTrainsGrequestDto payload the Parameter OnlyLastDay = true. Currently unsure which impact on controller side this has.

**Comment by dominoxp** [comment]
Currently waiting for @AlexanderZender on updates in controller to fix the behaviour of GetTrainingRequestDTO Parameter OnlyLastDay = true not returning current running or other trainings from the same day

**Comment by AlexanderZender** [comment]
Fix has been submitted
