### ISSUE TITLE
UI Training Online Prediction

### ISSUE THREAD

**Issue by dominoxp** [hochschule-darmstadt/MetaAutoML#412]
**Describe the bug**
A clear and concise description of what the bug is (if applicable, add screenshots)
When using a large dataset for prediction the Prediction Preview Title and Close button is hidden when scrolling

![grafik](https://github.com/hochschule-darmstadt/MetaAutoML/assets/13829738/91bb89c0-39b3-41ad-b932-9e35e9bef342)

**To Reproduce**
Steps to reproduce the behavior ((if applicable, add screenshots)):
1. Go to a past Training
2. Click on any Model which trained successful
3. Add a Live dataset, eg. the Titanic sample set 
4. Upload and wait for prediction
5. Click on show Prediction

**Expected behavior**
A clear and concise description of what you expect to happen.
The Preview Popup Title and Close Button should always be visible

**Comment by BernhardHumm** [comment]
I would restrict the prediction table to, say, 20 rows for large datasets.
