### ISSUE TITLE
increase max incoming grpc message size in frontend.

### ISSUE THREAD

**Issue by Jonas-Wessner** [hochschule-darmstadt/MetaAutoML#44]
The output given by the automls can be fairly big (e.g. the one produced by sklearn). The current message size (probably the default of 4MB) is not enough and must be increased in the frontend.
Whether the size is sufficient can be tested when clicking on the download button in the fronend. Especially sklearn is currently broken and shall be fixed.

ERR MESSAGE:
```
error
Operation FailedStatus(StatusCode="ResourceExhausted", Detail="Received message exceeds the maximum configured message size.") : 404
```

**Comment by kehuydietlatoi** [comment]
Do you mean the download button in sessions card ?

**Comment by Jonas-Wessner** [comment]
yes, but you will have to wait for the merge requests of issue 35 to be merged. The issue does not exist on the main branch yet
