### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by FabioBurillo** [hochschule-darmstadt/MetaAutoML#46]
The login page should be redesigned according to the following wireframe:

![Screenshot 2022-01-16 at 11 47 03](https://user-images.githubusercontent.com/82576940/149656830-0864659b-f8e5-4609-929d-6e3cba9087be.png)

**Comment by al-becker** [comment]
I changed the colors added the current version of the logo and removed the external logins (via google facebook etc.)

![login](https://user-images.githubusercontent.com/33692777/150777557-d5be42db-2fc7-4d52-8acf-823d840fe71d.png)
