### ISSUE TITLE
General page structure (header, footer, sidebar)

### ISSUE THREAD

**Issue by FabioBurillo** [hochschule-darmstadt/MetaAutoML#47]
The general page structure should be redesigned according to the following wireframe:

![Screenshot 2022-01-16 at 11 50 14](https://user-images.githubusercontent.com/82576940/149656909-c098f854-5a3f-438f-a958-a9dbb6e08779.png)

**Comment by kehuydietlatoi** [comment]
![image](https://user-images.githubusercontent.com/52171839/150175749-4b513b62-1ba1-4d07-a400-aeffb358205f.png)
@FabioBurillo  @al-becker  I removed toggle button for side bar and refactor to new design , can anyone give me feedback.

**Comment by FabioBurillo** [comment]
The Datasets text and icons looks nice. 
I think the session isn't needed in the left drawer.

The mame of the Application should be changed, but I think that is a bug right now. It should already be fixed.
The claim is a slogan that should be later displayed on the header.
Have you seen if there is the possibility to make the header span the full width?
This is kinda needed before we add the claim etc.

Are the buttons on the top right dropdown menus with the correct links?

**Comment by kehuydietlatoi** [comment]
I will remove session as soon as we merge your dataset page branch.
I don't know exactly what is our slogan so i just left dummy "claim" there.
I have searched but did not find a solution for full with header span, a suggestion from me is we remove left drawer or use another component.
"Are the buttons on the top right dropdown menus with the correct links?"  yes i linked it with /help and .impressum

**Comment by BernhardHumm** [comment]
Claim: 

Effective Machine Learning made easy
