### ISSUE TITLE
Datasets page

### ISSUE THREAD

**Issue by FabioBurillo** [hochschule-darmstadt/MetaAutoML#48]
A new page "Datasets" should be created (maybe parts from our wizard step 1 page can be reused).
This page should be designed according to the following wireframe.
The menu on the left may be implemented as a ...-icon with a small dropdown menu.
The second window should be a [dialog](https://www.matblazor.com/Dialog) opened by clicking on the "Add dataset"-button

![Screenshot 2022-01-16 at 11 53 24](https://user-images.githubusercontent.com/82576940/149656987-e1bed211-06f9-414a-a679-aec5cbe0c8ed.png)

**Comment by kehuydietlatoi** [comment]
![image](https://user-images.githubusercontent.com/52171839/149677550-5c368f49-f75b-4b53-b37b-6266bf047bc8.png)
Do we need upload button ? Current version when input field file name is blank then dataset name is it's default name.

**Comment by kehuydietlatoi** [comment]
![image](https://user-images.githubusercontent.com/52171839/149689117-ed5326f3-5e99-41a9-80cf-530482ae8f30.png)
Maybe we can use 2 icons instead of drop down menü. (I implemented dropdown menu on branch 48 frontend)

**Comment by BernhardHumm** [comment]
This dialog is not intuitive. Should you enter a file name instead of selecting it?

What does a button mean descripted by “Click or drag&drop?”.

Why have both interface elements different sizes?

**Comment by kehuydietlatoi** [comment]
> This dialog is not intuitive. Should you enter a file name instead of selecting it? What does a button mean descripted by “Click or drag&drop?”. Why have both interface elements different sizes?
Is "Name" field above in wireframe picture current uploaded file's name ? (If yes , i think i misunderstood. I thought that field is a custome input field name for dataset.)
Button "Clicl drag and drop" is for uploading data, because of the description makes the both interface elements have different sizes (i will fix it now.)

**Comment by al-becker** [comment]
No the "Name" field is independent of the upload file name. (For now we cannot save this new Name in the Controller, we probably want to add a database before saving it.)

**Comment by al-becker** [comment]
aktueller stand 
![aktueller stand](https://user-images.githubusercontent.com/33692777/149762413-f5540c90-2b28-4d94-87ee-889a875bed2c.png)

TODO:
- format date to yyyy-MM-dd
- Remove "Start new Run" + Buttons
- change button design (for the button in the rows)
