### ISSUE TITLE
Training page

### ISSUE THREAD

**Issue by FabioBurillo** [hochschule-darmstadt/MetaAutoML#50]
A new page "Training" should be created and designed according to the following wireframe:

![Screenshot 2022-01-16 at 12 11 04](https://user-images.githubusercontent.com/82576940/149657485-19349ed3-a0e9-4bbb-90dc-6a21e8420246.png)

It should contain two tabs "Leaderboard" and "Configuration".

- [ ] **Tab "Leaderboard"**

![Screenshot 2022-01-16 at 12 11 56](https://user-images.githubusercontent.com/82576940/149657525-612e11c8-5a95-486a-ba02-1b1ae50e59c9.png)

- [ ] **Tab "Configuration"**  

![Screenshot 2022-01-16 at 12 12 38](https://user-images.githubusercontent.com/82576940/149657547-86063d19-746f-40bc-ab68-a487f3a48136.png)

**Comment by al-becker** [comment]
![leaderboard](https://user-images.githubusercontent.com/33692777/150686647-cca185ff-91c0-4915-af3d-e344385be995.png)
