### ISSUE TITLE
The search function is not working

### ISSUE THREAD

**Issue by Keszwel** [hochschule-darmstadt/MetaAutoML#542]
**Describe the bug**
When searching something in the top "Help Search" field the first search result always shows the same page.
![grafik](https://github.com/user-attachments/assets/83425773-60cb-4158-9fde-cd86dc196306)
**To Reproduce**
Type anything in the "Help Search" field, then confirm search.
1. Start from anywhere
2. Click on "Help Search" field
3. Type in the field any OMA-ML related term 
4. See always the same Introduction page

**Expected behavior**
See the search result

**Comment by BernhardHumm** [comment]
Please specify more precicely
