### ISSUE TITLE
Test of the Application

### ISSUE THREAD

**Issue by al-becker** [hochschule-darmstadt/MetaAutoML#55]
_Found Bugs:_
-----
~~uploading some datasets results in errors in the controller that break application because no more datasets can be read~~ FIXED
-----
unremoved ...-export.zip files cause the adapter to crash -> remove the automatically before creating
-----

_Needs to be investigated:_
-----
training time:
~~when selecting 30 seconds mljar trains only for 13 --> needs to be looked at~~ FIXED
-----
~~AutoCVE can only handle numerical values and only classification -> categories that are possible to cast to numerical need to be transformed in the adapter~~ FIXED
-----

**Comment by kehuydietlatoi** [comment]
Found Bugs:
MLJAR is not displayed in chips list.
