### ISSUE TITLE
How to start the Controller module locally: short instructions

### ISSUE THREAD

**Issue by shamilnabiyev** [hochschule-darmstadt/MetaAutoML#71]
### How to start the Controller module locally: short instructions

1. Create a new virtual environment in MetaAutoML directory and activate it. Check out this tutorial: [Configure a virtual environment in PyCharm﻿](https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html)
2. Open the Terminal/CLI and install the dependencies: `pip install -r controller\requirements.txt `
3. Open the python interpreter settings in PyCharm: `File > Settings > Project:MetaAutoML > Python Interpreter`
4. On the top right side click on the settings (`gear`) icon and select the "Show all" option
5. Select the python interpreter (virtualenv) from the list.
6. Click the folder icon on the bottom side of the current window.
7. A new "Interpreter Paths" window will be opened
8. Click on the plus button. Then, select the `MetaAutoML/controller/interfaces` directory
9. Repeat the previous step for other module directories: 
	`MetaAutoML/controller/managers`
	`MetaAutoML/controller/managers/adaptermanagers`
	`MetaAutoML/controller/sessions`
	`MetaAutoML/controller/utils`
	`MetaAutoML/adapters/GRPC/Adapter`
	`MetaAutoML/adapters/GRPC/Controller`
	`MetaAutoML/adapters/Utils/AutoMLs`
	`MetaAutoML/adapters/Utils/Utils`
10. Click the OK button to confirm the changes (see Screenshot-1 below).
11. Open the Run Configurations, select the Controller config (see Screenshot-2 below), and add the following string to Environment Variables:
	`PYTHONUNBUFFERED=1;PYTHON_ENV=python;MLJAR_SERVICE_HOST=localhost;MLJAR_SERVICE_PORT=50059;AUTOCVE_SERVICE_HOST=localhost;AUTOCVE_SERVICE_PORT=50058;FLAML_SERVICE_HOST=localhost;FLAML_SERVICE_PORT=50056;SKLEARN_SERVICE_HOST=localhost;SKLEARN_SERVICE_PORT=50055;PYTORCH_SERVICE_HOST=localhost;PYTORCH_SERVICE_PORT=50059;AUTOGLUON_SERVICE_HOST=localhost;AUTOGLUON_SERVICE_PORT=50057;AUTOKERAS_SERVICE_HOST=localhost;AUTOKERAS_SERVICE_PORT=50052` 
12. Lastly, restart the PyCharm IDE from the menu: `"File" -> "Invalidate Caches / Restart" -> Click on the "Invalidate Caches / Restart"` button

<hr>

*Screenshot-1:*

![import1](https://user-images.githubusercontent.com/22834492/167393568-49986423-8398-4212-a74b-c25f5c3263e2.png)

*Screenshot-2:*

![import21](https://user-images.githubusercontent.com/22834492/167393868-30836293-74d9-4d46-9b0b-2f7beb0b99c8.png)

*Screenshot-3:*

![import2](https://user-images.githubusercontent.com/22834492/167393697-ea58307a-7a41-41bc-9ee4-dc53641f8257.png)

**Comment by shamilnabiyev** [comment]
Updated the environment variables to `PYTHONUNBUFFERED=1;PYTHON_ENV=python;MLJAR_SERVICE_HOST=0.0.0.0;MLJAR_SERVICE_PORT=50059;AUTOCVE_SERVICE_HOST=0.0.0.0;AUTOCVE_SERVICE_PORT=50058;FLAML_SERVICE_HOST=0.0.0.0;FLAML_SERVICE_PORT=50056;SKLEARN_SERVICE_HOST=0.0.0.0;SKLEARN_SERVICE_PORT=50055;PYTORCH_SERVICE_HOST=0.0.0.0;PYTORCH_SERVICE_PORT=50059;AUTOGLUON_SERVICE_HOST=0.0.0.0;AUTOGLUON_SERVICE_PORT=50057;AUTOKERAS_SERVICE_HOST=0.0.0.0;AUTOKERAS_SERVICE_PORT=50052`

**Comment by jnnks** [comment]
We should streamline the process and make it as transparent as possible.
Ideally we have configurations for popular IDEs that "just work".

In the meantime, could you add your guide to the wiki @shamilnabiyev. I think it would be of great help and more visible there :)

**Comment by shamilnabiyev** [comment]
Moved to the Wiki: [How to start the controller module locally](https://github.com/hochschule-darmstadt/MetaAutoML/wiki/How-to-start-the-Controller-module-locally-(workaround))
